# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
        env:
          REACT_APP_GRAPHQL_URI : ${{ secrets.REACT_APP_GRAPHQL_URI }}
          REACT_APP_GRAPHQL_URI_DEV_MODE : ${{ secrets.REACT_APP_GRAPHQL_URI_DEV_MODE }}
          REACT_APP_SUB_URI : ${{ secrets.REACT_APP_SUB_URI }}
          REACT_APP_SUB_URI_DEV_MODE : ${{ secrets.REACT_APP_SUB_URI_DEV_MODE }}
          REACT_APP_TOKEN_URI: ${{ secrets.REACT_APP_TOKEN_URI}}
